[project]
name = "masking-program"
version = "1.0.0"
description = "TinyIT Program for Encryption and Decryption using Masking Techniques"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
authors = [
    {name = "Jose Ibay", email = "ourcatisfat@gmail.com"}]